# Generated by Django 3.0.1 on 2019-12-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191222_0505'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-date',), 'verbose_name': 'Match', 'verbose_name_plural': 'Matchs'},
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default='2019-01-01', verbose_name='match date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='winning_stat',
            field=models.CharField(max_length=64, null=True, verbose_name='Winning stats'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='teams.Team'),
        ),
    ]
