# Generated by Django 3.0.1 on 2019-12-22 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name="Team's Point")),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_point', to='teams.Team')),
            ],
            options={
                'verbose_name': 'PointTable',
                'verbose_name_plural': 'PointTable',
                'ordering': ('-points',),
            },
        ),
    ]
