# Generated by Django 3.0.1 on 2019-12-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191222_0505'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamPoint',
            new_name='PointTable',
        ),
        migrations.AlterModelOptions(
            name='pointtable',
            options={'ordering': ('-points',), 'verbose_name': 'PointTable', 'verbose_name_plural': 'PointTable'},
        ),
    ]
