# Generated by Django 3.0.1 on 2019-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Team Name')),
                ('logouri', models.URLField(verbose_name='Team Logo URI')),
                ('club_state', models.CharField(max_length=32, verbose_name='Club State')),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ('-name',),
            },
        ),
    ]
