# Generated by Django 3.0.1 on 2019-12-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-name',), 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
